# Generated by Django 4.2.5 on 2023-10-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otdels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('javobgar', models.CharField(max_length=100)),
                ('topshiriq_nomer', models.CharField(max_length=100)),
                ('topshiriq_sana', models.DateField()),
                ('topshiriq_mavzu', models.CharField(max_length=100)),
                ('topshirq_muddat', models.DateField()),
                ('topshiriq_otdel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.otdels')),
                ('topshiriq_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.type_task')),
            ],
        ),
    ]
